name: Installer les outils

on:
  push:
    branches:
      - main

jobs:
  installer-dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt github
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Installer python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Vérifier les installations
        run: |
          echo "Node.js version:"
          node -v
          echo "Python version:"
          python --version
